version: '1.0'
services:
  db_test:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: test-filterdb
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "9998:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db2:/var/lib/mysql

volumes:
  mysql-db2: